/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'postId' : PostId,
});
export const NotificationType = IDL.Variant({
  'retweet' : IDL.Null,
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'mention' : IDL.Null,
  'follow' : IDL.Null,
});
export const LockoutStatus = IDL.Record({
  'failedCount' : IDL.Nat,
  'locked' : IDL.Bool,
  'lockedUntil' : IDL.Opt(Timestamp),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InviteStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'claimed' : IDL.Null,
});
export const InviteView = IDL.Record({
  'status' : InviteStatus,
  'expiresAt' : Timestamp,
  'code' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'claimedAt' : IDL.Opt(Timestamp),
  'claimedBy' : IDL.Opt(UserId),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostPrivacy = IDL.Variant({
  'followersOnly' : IDL.Null,
  'public' : IDL.Null,
});
export const CreatePostInput = IDL.Record({
  'content' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'privacy' : IDL.Opt(PostPrivacy),
});
export const PostView = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'retweetCount' : IDL.Nat,
  'privacy' : PostPrivacy,
  'commentCount' : IDL.Nat,
  'likedByMe' : IDL.Bool,
});
export const CreateProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'avatarType' : IDL.Opt(IDL.Text),
  'avatar3dConfig' : IDL.Opt(IDL.Text),
  'coverBlob' : IDL.Opt(ExternalBlob),
});
export const ProfileView = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'username' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'avatarType' : IDL.Text,
  'createdAt' : Timestamp,
  'isVerified' : IDL.Bool,
  'avatar3dConfig' : IDL.Opt(IDL.Text),
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'coverBlob' : IDL.Opt(ExternalBlob),
});
export const Page_1 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(PostView),
});
export const FlagStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'dismissed' : IDL.Null,
});
export const FlagTargetKind = IDL.Variant({
  'post' : IDL.Null,
  'user' : IDL.Null,
  'comment' : IDL.Null,
});
export const FlagView = IDL.Record({
  'id' : IDL.Nat,
  'status' : FlagStatus,
  'createdAt' : Timestamp,
  'resolution' : IDL.Opt(IDL.Text),
  'targetPrincipal' : IDL.Opt(UserId),
  'reportedBy' : UserId,
  'targetKind' : FlagTargetKind,
  'targetId' : IDL.Nat,
  'resolvedAt' : IDL.Opt(Timestamp),
  'resolvedBy' : IDL.Opt(UserId),
  'reason' : IDL.Text,
});
export const Mention = IDL.Record({
  'mentionedUserId' : UserId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'postId' : PostId,
});
export const Page_3 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(Mention),
});
export const AdminRole = IDL.Variant({
  'moderator' : IDL.Null,
  'owner' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'actorId' : UserId,
  'targetPostId' : IDL.Opt(PostId),
  'recipientId' : UserId,
  'targetUserId' : IDL.Opt(UserId),
});
export const Page_2 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(NotificationView),
});
export const ActionKind = IDL.Variant({
  'addModerator' : IDL.Null,
  'inviteRevoked' : IDL.Null,
  'removeComment' : IDL.Null,
  'tfaResend' : IDL.Null,
  'tfaSuccess' : IDL.Null,
  'removeModerator' : IDL.Null,
  'claimOwner' : IDL.Null,
  'inviteClaimed' : IDL.Null,
  'suspendUser' : IDL.Null,
  'tfaFailure' : IDL.Null,
  'dismissFlag' : IDL.Null,
  'removePost' : IDL.Null,
  'tfaLockout' : IDL.Null,
  'resolveFlag' : IDL.Null,
  'unsuspendUser' : IDL.Null,
});
export const ActivityLogView = IDL.Record({
  'id' : IDL.Nat,
  'action' : ActionKind,
  'note' : IDL.Opt(IDL.Text),
  'targetPrincipal' : IDL.Opt(UserId),
  'performedBy' : UserId,
  'timestamp' : Timestamp,
  'targetId' : IDL.Opt(IDL.Nat),
});
export const RoleEntry = IDL.Record({
  'grantedAt' : Timestamp,
  'grantedBy' : UserId,
  'userId' : UserId,
  'role' : AdminRole,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(ProfileView),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Opt(IDL.Text),
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'avatarType' : IDL.Opt(IDL.Text),
  'avatar3dConfig' : IDL.Opt(IDL.Text),
  'coverBlob' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
  'addModerator' : IDL.Func([UserId], [], []),
  'addNotification' : IDL.Func(
      [UserId, UserId, NotificationType, IDL.Opt(PostId), IDL.Opt(UserId)],
      [],
      [],
    ),
  'adminGetMyTelegramChatId' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'adminGetTelegramBotToken' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'adminGetTfaLockoutStatus' : IDL.Func([], [LockoutStatus], []),
  'adminRegisterTelegramChatId' : IDL.Func([IDL.Text], [], []),
  'adminRemoveComment' : IDL.Func([CommentId, IDL.Opt(IDL.Text)], [], []),
  'adminRemovePost' : IDL.Func([PostId, IDL.Opt(IDL.Text)], [], []),
  'adminRequestTfaCode' : IDL.Func([], [IDL.Text], []),
  'adminSetTelegramBotToken' : IDL.Func([IDL.Text], [], []),
  'adminSetVerified' : IDL.Func([UserId, IDL.Bool], [], []),
  'adminSuspendUser' : IDL.Func([UserId, IDL.Opt(IDL.Text)], [], []),
  'adminUnsuspendUser' : IDL.Func([UserId, IDL.Opt(IDL.Text)], [], []),
  'adminVerifyTfaCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([UserId], [], []),
  'claimModeratorInvite' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'claimOwner' : IDL.Func([], [IDL.Bool], []),
  'clearAllNotifications' : IDL.Func([], [], []),
  'createModeratorInvite' : IDL.Func([IDL.Text], [InviteView], []),
  'createPost' : IDL.Func([CreatePostInput], [PostView], []),
  'createProfile' : IDL.Func([CreateProfileInput], [ProfileView], []),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'dismissFlag' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'flagComment' : IDL.Func([CommentId, IDL.Text], [IDL.Nat], []),
  'flagPost' : IDL.Func([PostId, IDL.Text], [IDL.Nat], []),
  'flagUser' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'getFlag' : IDL.Func([IDL.Nat], [IDL.Opt(FlagView)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowingIds' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getMentionsForUser' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [Page_3],
      ['query'],
    ),
  'getModeratorInvite' : IDL.Func([IDL.Text], [IDL.Opt(InviteView)], ['query']),
  'getMutedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getMyAdminRole' : IDL.Func([], [IDL.Opt(AdminRole)], ['query']),
  'getMyNotifications' : IDL.Func([IDL.Nat, IDL.Nat], [Page_2], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
  'getOwner' : IDL.Func([], [IDL.Opt(UserId)], ['query']),
  'getPinnedPosts' : IDL.Func([UserId], [IDL.Vec(PostId)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProfileView)],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
  'isBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isMuted' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isUserSuspended' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'listActivityLog' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ActivityLogView)],
      ['query'],
    ),
  'listAllPosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'listComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'listFlags' : IDL.Func([IDL.Opt(FlagStatus)], [IDL.Vec(FlagView)], ['query']),
  'listModeratorInvites' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(InviteView)],
      ['query'],
    ),
  'listModerators' : IDL.Func([], [IDL.Vec(RoleEntry)], ['query']),
  'listPostsByUser' : IDL.Func([UserId, IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'listProfiles' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'muteUser' : IDL.Func([UserId], [], []),
  'pinPost' : IDL.Func([PostId], [], []),
  'removeModerator' : IDL.Func([UserId], [], []),
  'resolveFlag' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'revokeModeratorInvite' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([CreateProfileInput], [], []),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(ProfileView)], ['query']),
  'toggleLike' : IDL.Func([PostId], [IDL.Nat, IDL.Bool], []),
  'transformWrapper' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unblockUser' : IDL.Func([UserId], [], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'unmuteUser' : IDL.Func([UserId], [], []),
  'unpinPost' : IDL.Func([PostId], [], []),
  'updateProfile' : IDL.Func([UpdateProfileInput], [ProfileView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'postId' : PostId,
  });
  const NotificationType = IDL.Variant({
    'retweet' : IDL.Null,
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'mention' : IDL.Null,
    'follow' : IDL.Null,
  });
  const LockoutStatus = IDL.Record({
    'failedCount' : IDL.Nat,
    'locked' : IDL.Bool,
    'lockedUntil' : IDL.Opt(Timestamp),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InviteStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'claimed' : IDL.Null,
  });
  const InviteView = IDL.Record({
    'status' : InviteStatus,
    'expiresAt' : Timestamp,
    'code' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'claimedAt' : IDL.Opt(Timestamp),
    'claimedBy' : IDL.Opt(UserId),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostPrivacy = IDL.Variant({
    'followersOnly' : IDL.Null,
    'public' : IDL.Null,
  });
  const CreatePostInput = IDL.Record({
    'content' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'privacy' : IDL.Opt(PostPrivacy),
  });
  const PostView = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'retweetCount' : IDL.Nat,
    'privacy' : PostPrivacy,
    'commentCount' : IDL.Nat,
    'likedByMe' : IDL.Bool,
  });
  const CreateProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'avatarType' : IDL.Opt(IDL.Text),
    'avatar3dConfig' : IDL.Opt(IDL.Text),
    'coverBlob' : IDL.Opt(ExternalBlob),
  });
  const ProfileView = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'username' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'avatarType' : IDL.Text,
    'createdAt' : Timestamp,
    'isVerified' : IDL.Bool,
    'avatar3dConfig' : IDL.Opt(IDL.Text),
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'coverBlob' : IDL.Opt(ExternalBlob),
  });
  const Page_1 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(PostView),
  });
  const FlagStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'dismissed' : IDL.Null,
  });
  const FlagTargetKind = IDL.Variant({
    'post' : IDL.Null,
    'user' : IDL.Null,
    'comment' : IDL.Null,
  });
  const FlagView = IDL.Record({
    'id' : IDL.Nat,
    'status' : FlagStatus,
    'createdAt' : Timestamp,
    'resolution' : IDL.Opt(IDL.Text),
    'targetPrincipal' : IDL.Opt(UserId),
    'reportedBy' : UserId,
    'targetKind' : FlagTargetKind,
    'targetId' : IDL.Nat,
    'resolvedAt' : IDL.Opt(Timestamp),
    'resolvedBy' : IDL.Opt(UserId),
    'reason' : IDL.Text,
  });
  const Mention = IDL.Record({
    'mentionedUserId' : UserId,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'postId' : PostId,
  });
  const Page_3 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(Mention),
  });
  const AdminRole = IDL.Variant({ 'moderator' : IDL.Null, 'owner' : IDL.Null });
  const NotificationView = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'actorId' : UserId,
    'targetPostId' : IDL.Opt(PostId),
    'recipientId' : UserId,
    'targetUserId' : IDL.Opt(UserId),
  });
  const Page_2 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(NotificationView),
  });
  const ActionKind = IDL.Variant({
    'addModerator' : IDL.Null,
    'inviteRevoked' : IDL.Null,
    'removeComment' : IDL.Null,
    'tfaResend' : IDL.Null,
    'tfaSuccess' : IDL.Null,
    'removeModerator' : IDL.Null,
    'claimOwner' : IDL.Null,
    'inviteClaimed' : IDL.Null,
    'suspendUser' : IDL.Null,
    'tfaFailure' : IDL.Null,
    'dismissFlag' : IDL.Null,
    'removePost' : IDL.Null,
    'tfaLockout' : IDL.Null,
    'resolveFlag' : IDL.Null,
    'unsuspendUser' : IDL.Null,
  });
  const ActivityLogView = IDL.Record({
    'id' : IDL.Nat,
    'action' : ActionKind,
    'note' : IDL.Opt(IDL.Text),
    'targetPrincipal' : IDL.Opt(UserId),
    'performedBy' : UserId,
    'timestamp' : Timestamp,
    'targetId' : IDL.Opt(IDL.Nat),
  });
  const RoleEntry = IDL.Record({
    'grantedAt' : Timestamp,
    'grantedBy' : UserId,
    'userId' : UserId,
    'role' : AdminRole,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(ProfileView),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Opt(IDL.Text),
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'avatarType' : IDL.Opt(IDL.Text),
    'avatar3dConfig' : IDL.Opt(IDL.Text),
    'coverBlob' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
    'addModerator' : IDL.Func([UserId], [], []),
    'addNotification' : IDL.Func(
        [UserId, UserId, NotificationType, IDL.Opt(PostId), IDL.Opt(UserId)],
        [],
        [],
      ),
    'adminGetMyTelegramChatId' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'adminGetTelegramBotToken' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'adminGetTfaLockoutStatus' : IDL.Func([], [LockoutStatus], []),
    'adminRegisterTelegramChatId' : IDL.Func([IDL.Text], [], []),
    'adminRemoveComment' : IDL.Func([CommentId, IDL.Opt(IDL.Text)], [], []),
    'adminRemovePost' : IDL.Func([PostId, IDL.Opt(IDL.Text)], [], []),
    'adminRequestTfaCode' : IDL.Func([], [IDL.Text], []),
    'adminSetTelegramBotToken' : IDL.Func([IDL.Text], [], []),
    'adminSetVerified' : IDL.Func([UserId, IDL.Bool], [], []),
    'adminSuspendUser' : IDL.Func([UserId, IDL.Opt(IDL.Text)], [], []),
    'adminUnsuspendUser' : IDL.Func([UserId, IDL.Opt(IDL.Text)], [], []),
    'adminVerifyTfaCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([UserId], [], []),
    'claimModeratorInvite' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'claimOwner' : IDL.Func([], [IDL.Bool], []),
    'clearAllNotifications' : IDL.Func([], [], []),
    'createModeratorInvite' : IDL.Func([IDL.Text], [InviteView], []),
    'createPost' : IDL.Func([CreatePostInput], [PostView], []),
    'createProfile' : IDL.Func([CreateProfileInput], [ProfileView], []),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'dismissFlag' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'flagComment' : IDL.Func([CommentId, IDL.Text], [IDL.Nat], []),
    'flagPost' : IDL.Func([PostId, IDL.Text], [IDL.Nat], []),
    'flagUser' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
    'getFlag' : IDL.Func([IDL.Nat], [IDL.Opt(FlagView)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowingIds' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getMentionsForUser' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [Page_3],
        ['query'],
      ),
    'getModeratorInvite' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InviteView)],
        ['query'],
      ),
    'getMutedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getMyAdminRole' : IDL.Func([], [IDL.Opt(AdminRole)], ['query']),
    'getMyNotifications' : IDL.Func([IDL.Nat, IDL.Nat], [Page_2], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
    'getOwner' : IDL.Func([], [IDL.Opt(UserId)], ['query']),
    'getPinnedPosts' : IDL.Func([UserId], [IDL.Vec(PostId)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProfileView)],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
    'isBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isMuted' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isUserSuspended' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'listActivityLog' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ActivityLogView)],
        ['query'],
      ),
    'listAllPosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
    'listComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'listFlags' : IDL.Func(
        [IDL.Opt(FlagStatus)],
        [IDL.Vec(FlagView)],
        ['query'],
      ),
    'listModeratorInvites' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(InviteView)],
        ['query'],
      ),
    'listModerators' : IDL.Func([], [IDL.Vec(RoleEntry)], ['query']),
    'listPostsByUser' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [Page_1],
        ['query'],
      ),
    'listProfiles' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'muteUser' : IDL.Func([UserId], [], []),
    'pinPost' : IDL.Func([PostId], [], []),
    'removeModerator' : IDL.Func([UserId], [], []),
    'resolveFlag' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'revokeModeratorInvite' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([CreateProfileInput], [], []),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(ProfileView)], ['query']),
    'toggleLike' : IDL.Func([PostId], [IDL.Nat, IDL.Bool], []),
    'transformWrapper' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unblockUser' : IDL.Func([UserId], [], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'unmuteUser' : IDL.Func([UserId], [], []),
    'unpinPost' : IDL.Func([PostId], [], []),
    'updateProfile' : IDL.Func([UpdateProfileInput], [ProfileView], []),
  });
};

export const init = ({ IDL }) => { return []; };