/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'content' : string,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'postId' : PostId,
}
export type CommentId = bigint;
export interface CreatePostInput {
  'content' : string,
  'imageBlob' : [] | [ExternalBlob],
}
export interface CreateProfileInput {
  'bio' : string,
  'username' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'coverBlob' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface Page {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<ProfileView>,
}
export interface Page_1 {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<PostView>,
}
export type PostId = bigint;
export interface PostView {
  'id' : PostId,
  'likeCount' : bigint,
  'content' : string,
  'imageBlob' : [] | [ExternalBlob],
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'commentCount' : bigint,
  'likedByMe' : boolean,
}
export interface ProfileView {
  'id' : UserId,
  'bio' : string,
  'postCount' : bigint,
  'username' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'followerCount' : bigint,
  'followingCount' : bigint,
  'coverBlob' : [] | [ExternalBlob],
}
export type Timestamp = bigint;
export interface UpdateProfileInput {
  'bio' : [] | [string],
  'username' : [] | [string],
  'avatarBlob' : [] | [ExternalBlob],
  'coverBlob' : [] | [ExternalBlob],
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[PostId, string], Comment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[CreatePostInput], PostView>,
  'createProfile' : ActorMethod<[CreateProfileInput], ProfileView>,
  'deleteComment' : ActorMethod<[CommentId], undefined>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [ProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[bigint, bigint], Page_1>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowingIds' : ActorMethod<[], Array<UserId>>,
  'getMyProfile' : ActorMethod<[], [] | [ProfileView]>,
  'getPost' : ActorMethod<[PostId], [] | [PostView]>,
  'getProfile' : ActorMethod<[UserId], [] | [ProfileView]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [ProfileView]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [ProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[UserId], boolean>,
  'listAllPosts' : ActorMethod<[bigint, bigint], Page_1>,
  'listComments' : ActorMethod<[PostId], Array<Comment>>,
  'listPostsByUser' : ActorMethod<[UserId, bigint, bigint], Page_1>,
  'listProfiles' : ActorMethod<[bigint, bigint], Page>,
  'saveCallerUserProfile' : ActorMethod<[CreateProfileInput], undefined>,
  'searchPosts' : ActorMethod<[string], Array<PostView>>,
  'searchUsers' : ActorMethod<[string], Array<ProfileView>>,
  'toggleLike' : ActorMethod<[PostId], [bigint, boolean]>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'updateProfile' : ActorMethod<[UpdateProfileInput], ProfileView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];