/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'postId' : PostId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreatePostInput = IDL.Record({
  'content' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
});
export const PostView = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'commentCount' : IDL.Nat,
  'likedByMe' : IDL.Bool,
});
export const CreateProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'coverBlob' : IDL.Opt(ExternalBlob),
});
export const ProfileView = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'username' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'coverBlob' : IDL.Opt(ExternalBlob),
});
export const Page_1 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(PostView),
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(ProfileView),
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Opt(IDL.Text),
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'coverBlob' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([CreatePostInput], [PostView], []),
  'createProfile' : IDL.Func([CreateProfileInput], [ProfileView], []),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowingIds' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProfileView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'listAllPosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'listComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'listPostsByUser' : IDL.Func([UserId, IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'listProfiles' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'saveCallerUserProfile' : IDL.Func([CreateProfileInput], [], []),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(ProfileView)], ['query']),
  'toggleLike' : IDL.Func([PostId], [IDL.Nat, IDL.Bool], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'updateProfile' : IDL.Func([UpdateProfileInput], [ProfileView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'postId' : PostId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreatePostInput = IDL.Record({
    'content' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
  });
  const PostView = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'commentCount' : IDL.Nat,
    'likedByMe' : IDL.Bool,
  });
  const CreateProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'coverBlob' : IDL.Opt(ExternalBlob),
  });
  const ProfileView = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'username' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'coverBlob' : IDL.Opt(ExternalBlob),
  });
  const Page_1 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(PostView),
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(ProfileView),
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Opt(IDL.Text),
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'coverBlob' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([CreatePostInput], [PostView], []),
    'createProfile' : IDL.Func([CreateProfileInput], [ProfileView], []),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowingIds' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProfileView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'listAllPosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
    'listComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'listPostsByUser' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [Page_1],
        ['query'],
      ),
    'listProfiles' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'saveCallerUserProfile' : IDL.Func([CreateProfileInput], [], []),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(ProfileView)], ['query']),
    'toggleLike' : IDL.Func([PostId], [IDL.Nat, IDL.Bool], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'updateProfile' : IDL.Func([UpdateProfileInput], [ProfileView], []),
  });
};

export const init = ({ IDL }) => { return []; };